DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user
(
    id BIGINT NOT NULL COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT NULL DEFAULT NULL COMMENT '年龄',
    phone VARCHAR(50) NULL DEFAULT NULL COMMENT '手机号',
    password VARCHAR(50) NULL DEFAULT NULL COMMENT '密码',
    address VARCHAR(50) NULL DEFAULT NULL COMMENT '地址',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    status INT DEFAULT 1 COMMENT '状态',
    version INT NULL DEFAULT NULL COMMENT '版本',
    deleted INT NULL DEFAULT NULL COMMENT '是否删除，1是删除',
    PRIMARY KEY (id)
);